<a href="https://colab.research.google.com/github/Gnana212/Gnanalakshmi_212/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
print(np.__version__)

1.21.6


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
n = np.zeros((3,4))
print(n.size * n.itemsize)

96 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np
n = np.zeros(10)
n[4] = 1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np
n = np.arange(50)
n1 = n[::-1]
print(n1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np
n = np.arange(9).reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
import numpy as np
n = np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
import numpy as np
n = np.random.random((3,3,3))
print(n)

[[[0.65383678 0.25230909 0.09590831]
  [0.6679517  0.52716094 0.9687285 ]
  [0.25135717 0.73436944 0.49206695]]

 [[0.83977892 0.92535519 0.23266277]
  [0.36312548 0.53659714 0.41198605]
  [0.86258471 0.29536279 0.02238195]]

 [[0.81726625 0.45023382 0.67359863]
  [0.94265857 0.43219989 0.36765269]
  [0.45558984 0.34182623 0.60662716]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
import numpy as np
n = np.random.random((10,10))
nmin,nmax = n.min(),n.max()
print(nmin, nmax)

0.008106169565932353 0.9997166034299487


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np
n = np.random.random(30)
n1 = n.mean()
print(n1)

0.523051261296916


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
n = np.ones((10,10))
n[1:-1,1:-1] = 0
print(n)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
import numpy as np
n = np.ones((3,3))
print(n)
n = np.pad(n, pad_width=1, mode='constant', constant_values=0)
print(n)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
import numpy as np
n = np.diag(1+np.arange(4),k=-1)
print(n)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
import numpy as np
n = np.zeros((8,8),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
import numpy as np
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
import numpy as np
n = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(n)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
import numpy as np
n = np.random.random((5,5))
nmax, nmin = n.max(), n.min()
n = (n - nmin)/(nmax - nmin)
print(n)


[[0.7924287  0.03978685 0.44813267 0.81367927 0.82879852]
 [0.         0.78606355 0.54637915 0.50767523 0.01864772]
 [0.01056445 0.86562829 0.36640011 0.90811759 0.34651427]
 [0.60836575 0.11201182 0.735698   0.32701202 0.20268514]
 [1.         0.21379727 0.91159176 0.16210059 0.86711327]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
import numpy as np
n = np.dot(np.ones((5,3)), np.ones((3,2)))
print(n)



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
import numpy as np
n = np.arange(11)
n[(3 < n) & (n <= 8)] *= -1
print(n)



[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
import numpy as np
n = np.random.uniform(-10,+10,10)
print(np.trunc(n+ np.copysign(0.5, n)))



[ 5. -8. -3. -6. -6.  3. -7. -2. -1.  3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
import numpy as np
n1 = np.random.randint(0,10,10)
n2 = np.random.randint(0,10,10)
print(np.intersect1d(n1,n2))



[0 2 4 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0



#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
No, False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
import numpy as np
y = np.datetime64('today') - np.timedelta64(1)
t = np.datetime64('today')
tom  = np.datetime64('today') + np.timedelta64(1)
print(y,t,tom)

2022-10-29 2022-10-30 2022-10-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
import numpy as np
n = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(n)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
import numpy as np
n = np.random.uniform(0,10,10)

print(n - n%1)
print(n // 1)
print(np.floor(n))
print(n.astype(int))
print(np.trunc(n))

[2. 3. 3. 7. 0. 4. 0. 1. 7. 6.]
[2. 3. 3. 7. 0. 4. 0. 1. 7. 6.]
[2. 3. 3. 7. 0. 4. 0. 1. 7. 6.]
[2 3 3 7 0 4 0 1 7 6]
[2. 3. 3. 7. 0. 4. 0. 1. 7. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [1]:
import numpy as np
n = np.zeros((5,5))
n += np.arange(5)
print(n)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [2]:
import numpy as np
def gen():
    for n in range(10):
        yield n
n1 = np.fromiter(gen(),dtype=float,count=-1)
print(n1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [3]:
import numpy as np
n = np.linspace(0,1,11,endpoint=False)[1:]
print(n)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [4]:
import numpy as np
n = np.random.random(10)
n.sort()
print(n)

[0.04112325 0.07144531 0.15947939 0.24123206 0.33136125 0.35714771
 0.62608685 0.62635107 0.68721363 0.72994148]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [5]:
import numpy as np
n = np.arange(10)
np.add.reduce(n)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [6]:
import numpy as np
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [11]:
import numpy as np
n = np.zeros(10)
n.flags.writeable = False
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [12]:
import numpy as np
n = np.random.random((10,2))
n1,n2 = n[:,0], n[:,1]
n3 = np.sqrt(n1**2+n2**2)
n4 = np.arctan2(n2,n1)
print(n3)
print(n4)

[0.43283124 0.97936353 0.8873387  0.99981891 0.99834657 0.99030798
 0.19191104 1.00049288 0.32540056 0.15784054]
[0.02073239 0.708291   0.32474707 1.56464576 0.37433954 0.2952186
 1.10988277 0.54917495 1.46358608 0.89708196]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [13]:
import numpy as np
n = np.random.random(10)
n[n.argmax()] = 0
print(n)

[0.22174899 0.12783306 0.         0.79895065 0.69621796 0.15064343
 0.56000336 0.73377028 0.428718   0.76578647]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [14]:
import numpy as np
n = np.zeros((5,5), [('n1',float),('n2',float)])
n['n1'], n['n2'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(n)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [15]:
import numpy as np
n = np.arange(8)
n1 = n + 0.5
n2 = 1.0 / np.subtract.outer(n, n1)
print(np.linalg.det(n2))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [16]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [17]:
import numpy as np
np.set_printoptions(threshold=float("inf"))
n = np.zeros((40,40))
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [18]:
import numpy as np
n = np.arange(100)
n1 = np.random.uniform(0,100)
index = (np.abs(n-n1)).argmin()
print(n[index])

0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [19]:
import numpy as np
n = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(n)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [20]:
import numpy as np
import scipy
import scipy.spatial
n = np.random.random((10,2))
n1,n2 = np.atleast_2d(n[:,0], n[:,1])
n3 = np.sqrt( (n1-n1.T)**2 + (n2-n2.T)**2)
print(n3)


n = np.random.random((10,2))
n3 = scipy.spatial.distance.cdist(n,n)
print(n3)

[[0.         0.29194522 0.41394937 0.44295003 0.37926595 0.34327075
  0.16109667 0.27144023 0.80465265 0.43181201]
 [0.29194522 0.         0.25197929 0.31517081 0.44948256 0.37436413
  0.45302235 0.23810756 0.76688856 0.20312918]
 [0.41394937 0.25197929 0.         0.0682062  0.31164113 0.6166148
  0.55262276 0.4822324  0.52326339 0.42902607]
 [0.44295003 0.31517081 0.0682062  0.         0.27268623 0.67220073
  0.56972806 0.53961779 0.45562167 0.49673597]
 [0.37926595 0.44948256 0.31164113 0.27268623 0.         0.70502983
  0.43251124 0.59789988 0.43815884 0.65245012]
 [0.34327075 0.37436413 0.6166148  0.67220073 0.70502983 0.
  0.42007335 0.13625711 1.10044878 0.32404926]
 [0.16109667 0.45302235 0.55262276 0.56972806 0.43251124 0.42007335
  0.         0.39335494 0.87061402 0.58176263]
 [0.27144023 0.23810756 0.4822324  0.53961779 0.59789988 0.13625711
  0.39335494 0.         0.97575216 0.22193566]
 [0.80465265 0.76688856 0.52326339 0.45562167 0.43815884 1.10044878
  0.87061402 0.975752

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [21]:
import numpy as np
n = (np.random.rand(10)*100).astype(np.float32)
n1 = n.view(np.int32)
n1[:] = n
print(n1)

[10 84 54 96 48  0 84 14 67 25]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [22]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
n = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(n)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [23]:
import numpy as np
n = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(n):
    print(index, value)
for index in np.ndindex(n.shape):
    print(index, n[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [24]:
import numpy as np
n, n1 = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
n2 = np.sqrt(n*n+n1*n1)
sigma, mu = 1.0, 0.0
n3 = np.exp(-( (n2-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(n3)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [25]:
import numpy as np
n = 10
n1 = 3
n2 = np.zeros((n,n))
np.put(n2, np.random.choice(range(n*n), n1, replace=False),1)
print(n2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [26]:
import numpy as np
n = np.random.rand(5, 10)
n1 = n - n.mean(axis=1, keepdims=True)
n1 = n - n.mean(axis=1).reshape(-1, 1)
print(n1)

[[ 0.06322764 -0.48730282  0.14487472 -0.10105286  0.11735117 -0.39808448
   0.25051791  0.32411762  0.28246818 -0.19611708]
 [ 0.37915198  0.34592206 -0.36833569 -0.02544561  0.2734264  -0.04182133
  -0.29409341  0.06555957 -0.00410891 -0.33025506]
 [ 0.38546043 -0.08551094  0.15790112  0.29247248 -0.44451115 -0.25083476
  -0.25740989 -0.12787731  0.1976131   0.13269692]
 [-0.29001975  0.16682211 -0.00273969 -0.31974    -0.32211587  0.07334684
   0.00473414  0.54801827 -0.41478449  0.55647846]
 [ 0.24251816 -0.12335653  0.09613036  0.16754477 -0.10591232  0.32948446
  -0.48001621 -0.0807228   0.26288356 -0.30855344]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [27]:
import numpy as np
n = np.random.randint(0,10,(3,3))
print(n)
print(n[n[:,1].argsort()])

[[8 9 5]
 [3 8 1]
 [9 1 6]]
[[9 1 6]
 [3 8 1]
 [8 9 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [28]:
import numpy as np
n = np.random.randint(0,3,(3,10))
print((~n.any(axis=0)).any())
n=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(n).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [29]:
import numpy as np
n = np.random.uniform(0,1,10)
n1 = 0.5
n2= n.flat[np.abs(n - n1).argmin()]
print(n2)

0.41314001236385356


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [30]:
import numpy as np
n = np.arange(3).reshape(3,1)
n1 = np.arange(3).reshape(1,3)
n2 = np.nditer([n,n1,None])
for n,n1,n3 in n2: n3[...] = n+ n1
print(n2.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [31]:
import numpy as np
class N1(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

n = N1(np.arange(10), "range_10")
print (n.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [33]:
import numpy as np
n = np.ones(10)
n1 = np.random.randint(0,len(n),20)
n += np.bincount(n1, minlength=len(n))
print(n)
np.add.at(n, n1, 1)
print(n)

[4. 1. 1. 2. 4. 4. 3. 5. 2. 4.]
[7. 1. 1. 3. 7. 7. 5. 9. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [34]:
import numpy as np
n = [1,2,3,4,5,6]
n1 = [1,3,9,3,4,1]
n2 = np.bincount(n1,n)
print(n2)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [35]:
import numpy as np
n, n1 = 256, 256
n2 = np.random.randint(0, 4, (n1, n, 3)).astype(np.ubyte)
colors = np.unique(n2.reshape(-1, 3), axis=0)
n3 = len(colors)
print(n3)
n, n1 = 256, 256
n3 = np.random.randint(0,4,(n1,n,3), dtype=np.uint8)
n324 = np.dot(n2.astype(np.uint32),[1,256,65536])
n3 = len(np.unique(n324))
print(n3)


64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [37]:
import numpy as np
n = np.random.randint(0,10,(3,4,3,4))
sum = n.sum(axis=(-2,-1))
print(sum)
sum = n.reshape(n.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[69 41 45 69]
 [72 40 49 66]
 [33 67 44 71]]
[[69 41 45 69]
 [72 40 49 66]
 [33 67 44 71]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [38]:
import numpy as np
import pandas as pd
n = np.random.uniform(0,1,100)
n1 = np.random.randint(0,10,100)
n_sums = np.bincount(n1, weights=n)
n_counts = np.bincount(n1)
n_means = n_sums / n_counts
print(n_means)
print(pd.Series(n).groupby(n1).mean())

[0.50531858 0.51497158 0.3901533  0.54794486 0.75489448 0.50427707
 0.41446495 0.51509004 0.39937405 0.47295209]
0    0.505319
1    0.514972
2    0.390153
3    0.547945
4    0.754894
5    0.504277
6    0.414465
7    0.515090
8    0.399374
9    0.472952
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [39]:
import numpy as np
n = np.random.uniform(0,1,(5,5))
n1 = np.random.uniform(0,1,(5,5))
np.diag(np.dot(n, n1))
np.sum(n * n1.T, axis=1)
np.einsum("ij,ji->i", n, n1)

array([0.67961473, 1.18652192, 1.15067425, 0.83399599, 1.41260947])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [40]:
import numpy as np
n = np.array([1,2,3,4,5])
n1 = 3
n0 = np.zeros(len(n) + (len(n)-1)*(n1))
n0[::n1+1] = n
print(n0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [41]:
import numpy as np
n = np.ones((5,5,3))
n1 = 2*np.ones((5,5))
print(n * n1[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [42]:
import numpy as np
n = np.arange(25).reshape(5,5)
n[[0,1]] = n[[1,0]]
print(n)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [44]:
import numpy as np
n = np.random.randint(0,100,(10,3))
n1 = np.roll(n.repeat(2,axis=1),-1,axis=1)
n1 = n1.reshape(len(n1)*3,2)
n1 = np.sort(n1,axis=1)
n2 = n1.view( dtype=[('p0',n1.dtype),('p1',n1.dtype)] )
n2 = np.unique(n2)
print(n2)

[( 1, 46) ( 1, 73) ( 4, 21) ( 4, 45) ( 5, 24) ( 5, 62) ( 9, 47) ( 9, 56)
 (14, 32) (14, 46) (17, 65) (17, 66) (21, 45) (24, 62) (28, 40) (28, 84)
 (32, 46) (37, 54) (37, 85) (40, 84) (44, 47) (44, 56) (46, 73) (47, 56)
 (49, 71) (49, 93) (54, 85) (65, 66) (71, 93)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [45]:
import numpy as np
n = np.bincount([1,1,2,3,4,4,6])
n1 = np.repeat(np.arange(len(n)), n)
print(n1)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [46]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
def average(n, n1=3) :
    n2 = np.cumsum(n1, dtype=float)
    n2[n1:] = n2[n1:] - n2[:-n1]
    return n2[n1 - 1:] / n1
n3 = np.arange(20)
print(average(n3, n1=3))

n3 = np.arange(20)
print(sliding_window_view(n3, window_shape=3).mean(axis=-1))

[]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [47]:
import numpy as np
from numpy.lib import stride_tricks
def dim(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
n = dim(np.arange(10), 3)
print(n)
n = np.arange(10)
print(sliding_window_view(n, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [48]:
import numpy as np
n = np.random.randint(0,2,100)
np.logical_not(n, out=n)

n = np.random.uniform(-1.0,1.0,100)
np.negative(n, out=n)

array([ 0.94587197, -0.31193629,  0.30470665,  0.65332583, -0.51741361,
       -0.40014932,  0.98136438,  0.26412131, -0.94353878,  0.46690728,
        0.06140093, -0.3282508 ,  0.415838  , -0.71997692,  0.5467856 ,
        0.90434896, -0.12484968, -0.59791719, -0.74094041, -0.41078627,
       -0.11423854,  0.15072092, -0.69466587,  0.65496278,  0.16874016,
       -0.41208868,  0.6418504 ,  0.77677613,  0.72913156,  0.88052052,
        0.82938243, -0.25324034, -0.45853767, -0.57175412, -0.20715721,
        0.04423026,  0.38435835, -0.3156444 ,  0.2133689 , -0.32404371,
        0.06295913, -0.98907925, -0.05689095, -0.43528853,  0.22527723,
        0.35201667,  0.44671222, -0.75699852, -0.77033507,  0.78360317,
       -0.10733249,  0.92294969,  0.32131488,  0.91913986,  0.13790545,
        0.39810945, -0.65661764,  0.26346721,  0.17455347, -0.58959152,
        0.20274025, -0.22985058,  0.30916318,  0.96885129, -0.2968382 ,
       -0.5699653 , -0.19406333, -0.284406  , -0.21594483,  0.76

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [49]:
import numpy as np
def dist(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(dist(P0, P1, p))

[ 7.67824498  7.22914985  5.11021984  2.08624839  3.58768782  5.85485234
  7.2776509  11.62793898 10.06181815  1.7783836 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [51]:
import numpy as np
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([dist(P0,P1,p_i) for p_i in p]))

[[3.60634582e+00 8.04542528e+00 8.93612690e+00 1.75714151e+00
  4.90461736e+00 8.05662675e+00 5.09600834e+00 1.02126114e+00
  5.22112528e+00 1.13217994e+00]
 [3.37652640e+00 1.18850695e+00 1.75647480e+00 4.92535955e+00
  2.02995253e+00 3.23193180e+00 3.54921548e+00 5.48672461e+00
  3.18766554e-03 5.77560051e+00]
 [2.67778310e+00 2.11998325e+00 1.95901497e+00 7.17687699e+00
  2.14836822e+00 6.07901118e+00 7.74885079e-01 4.05342407e+00
  2.58853165e+00 7.70302183e+00]
 [8.63022964e-01 4.08811096e+00 3.43358162e+00 7.65531568e+00
  4.78896811e+00 9.12633662e+00 3.77037192e+00 1.76883236e+00
  5.51567501e+00 7.89416827e+00]
 [3.37917793e+00 8.18589994e+00 7.93809475e+00 2.78747469e+00
  1.80667785e+00 1.14031310e+01 1.59121254e+00 1.96844042e+00
  8.11697624e+00 2.97291678e+00]
 [5.88487112e+00 9.96897537e+00 1.19388809e+01 7.67367507e+00
  1.15562585e+01 6.60612782e+00 1.13308736e+01 2.14426468e+00
  4.27888167e+00 6.73642430e+00]
 [5.19032243e+00 1.01852425e+01 9.33583938e+00 3.68317954e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [52]:
import numpy as np

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 6 4 4 3 1 8 6 8 4]
 [5 2 6 3 4 9 9 4 2 8]
 [1 9 0 3 8 4 3 7 1 8]
 [9 4 2 8 5 3 9 5 6 5]
 [9 2 6 3 3 4 0 4 2 2]
 [9 8 6 4 3 5 3 0 5 6]
 [6 5 1 5 9 3 5 6 4 6]
 [7 0 4 4 8 0 1 3 6 0]
 [0 7 8 3 0 6 9 5 3 1]
 [2 6 3 0 0 1 9 2 5 1]]
[[0 0 0 0 0]
 [0 2 6 4 4]
 [0 5 2 6 3]
 [0 1 9 0 3]
 [0 9 4 2 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [53]:
import numpy as np
n = np.arange(1,15,dtype=np.uint32)
n1 = stride_tricks.as_strided(n,(11,4),(4,4))
print(n1)
n = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(n, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [55]:
import numpy as np
n = np.random.uniform(0,1,(10,10))
n1, n2, n3 = np.linalg.svd(n) 
n4 = np.sum(n2 > 1e-10)
print(n4)
n4 = np.linalg.matrix_rank(n)
print(n4)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [56]:
import numpy as np
n = np.random.randint(0,10,50)
print(np.bincount(n).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [57]:
import numpy as np
n1 = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
n2 = stride_tricks.as_strided(n1, shape=(i, j, n, n), strides=n1.strides + n1.strides)
print(n2)
n1 = np.random.randint(0,5,(10,10))
print(sliding_window_view(n1, window_shape=(3, 3)))

[[[[3 0 1]
   [2 4 2]
   [2 0 4]]

  [[0 1 2]
   [4 2 0]
   [0 4 1]]

  [[1 2 2]
   [2 0 4]
   [4 1 2]]

  [[2 2 0]
   [0 4 4]
   [1 2 1]]

  [[2 0 0]
   [4 4 1]
   [2 1 0]]

  [[0 0 0]
   [4 1 4]
   [1 0 0]]

  [[0 0 2]
   [1 4 1]
   [0 0 3]]

  [[0 2 3]
   [4 1 4]
   [0 3 4]]]


 [[[2 4 2]
   [2 0 4]
   [1 0 4]]

  [[4 2 0]
   [0 4 1]
   [0 4 0]]

  [[2 0 4]
   [4 1 2]
   [4 0 2]]

  [[0 4 4]
   [1 2 1]
   [0 2 4]]

  [[4 4 1]
   [2 1 0]
   [2 4 4]]

  [[4 1 4]
   [1 0 0]
   [4 4 1]]

  [[1 4 1]
   [0 0 3]
   [4 1 3]]

  [[4 1 4]
   [0 3 4]
   [1 3 2]]]


 [[[2 0 4]
   [1 0 4]
   [0 0 0]]

  [[0 4 1]
   [0 4 0]
   [0 0 4]]

  [[4 1 2]
   [4 0 2]
   [0 4 2]]

  [[1 2 1]
   [0 2 4]
   [4 2 2]]

  [[2 1 0]
   [2 4 4]
   [2 2 0]]

  [[1 0 0]
   [4 4 1]
   [2 0 4]]

  [[0 0 3]
   [4 1 3]
   [0 4 2]]

  [[0 3 4]
   [1 3 2]
   [4 2 2]]]


 [[[1 0 4]
   [0 0 0]
   [0 2 1]]

  [[0 4 0]
   [0 0 4]
   [2 1 0]]

  [[4 0 2]
   [0 4 2]
   [1 0 4]]

  [[0 2 4]
   [4 2 2]
   [0 4 2]]

  [[2 4 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [58]:
import numpy as np
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  3  5 14  3]
 [ 3  8 11  8  7]
 [ 5 11  8 42  8]
 [14  8 42  9 13]
 [ 3  7  8 13  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [59]:
import numpy as np
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [60]:
import numpy as np
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [61]:
import numpy as np
def game(n):
    N = (n[0:-2,0:-2] + n[0:-2,1:-1] + n[0:-2,2:] +
         n[1:-1,0:-2]                + n[1:-1,2:] +
         n[2:  ,0:-2] + n[2:  ,1:-1] + n[2:  ,2:])
    n2 = (N==3) & (n[1:-1,1:-1]==0)
    n3 = ((N==2) | (N==3)) & (n[1:-1,1:-1]==1)
    n[...] = 0
    n[1:-1,1:-1][n2 | n3] = 1
    return n
n = np.random.randint(0,2,(50,50))
for i in range(100): n = game(n)
print(n)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [62]:
import numpy as np
n = np.arange(10000)
np.random.shuffle(n)
n1 = 5
print (n[np.argsort(n)[-n1:]])
print (n[np.argpartition(-n,n1)[:n1]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [63]:
import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [64]:
import numpy as np
n = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
n1 = np.core.records.fromarrays(n.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(n1)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [66]:
import numpy as np
z = np.random.rand(int(5e7))

%timeit np.power(z,3)
%timeit z*z*z
%timeit np.einsum('i,i,i->i',z,z,z)

3.73 s ± 17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
143 ms ± 644 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
144 ms ± 25.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [67]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [68]:
import numpy as np
n = np.random.randint(0,5,(10,3))
print(n)
n1 = np.all(n[:,1:] == n[:,:-1], axis=1)
n2 = n[~n1]
print(n2)
n2 = n[n.max(axis=1) != n.min(axis=1),:]
print(n1)

[[4 1 0]
 [1 4 1]
 [2 0 4]
 [1 0 1]
 [4 3 3]
 [1 0 4]
 [1 2 2]
 [2 4 3]
 [1 1 1]
 [1 3 0]]
[[4 1 0]
 [1 4 1]
 [2 0 4]
 [1 0 1]
 [4 3 3]
 [1 0 4]
 [1 2 2]
 [2 4 3]
 [1 3 0]]
[False False False False False False False False  True False]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [70]:
import numpy as np
n = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
n1 = ((n.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(n1[:,::-1])
n = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(n[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [71]:
import numpy as np
n = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(n).view(np.dtype((np.void, n.dtype.itemsize * n.shape[1])))
_, idx = np.unique(T, return_index=True)
n1 = n[idx]
print(n1)
n1 = np.unique(n, axis=0)
print(n1)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [72]:
import numpy as np
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)        
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.08883223, 0.04306384, 0.01481843, 0.07164074, 0.06642246,
        0.04527479, 0.06120918, 0.01167663, 0.04742373, 0.07333585],
       [0.45226135, 0.21924597, 0.07544337, 0.3647363 , 0.33816906,
        0.23050232, 0.31162728, 0.05944789, 0.24144302, 0.3733664 ],
       [0.16783549, 0.08136281, 0.02799725, 0.13535469, 0.12549551,
        0.08554008, 0.11564578, 0.02206129, 0.0896002 , 0.13855735],
       [0.4686122 , 0.22717249, 0.07817092, 0.3779228 , 0.35039507,
        0.23883579, 0.32289371, 0.06159715, 0.25017203, 0.38686491],
       [0.01919925, 0.00930736, 0.0032027 , 0.01548366, 0.01435584,
        0.00978521, 0.0132291 , 0.00252366, 0.01024966, 0.01585002],
       [0.76924969, 0.37291467, 0.12832136, 0.62037864, 0.57519052,
        0.39206056, 0.53004571, 0.10111471, 0.41066955, 0.63505754],
       [0.61058205, 0.29599622, 0.10185343, 0.49241756, 0.45655008,
        0.31119303, 0.42071696, 0.0802585 , 0.32596367, 0.50406875],
       [0.32960946, 0.15978713, 0.0549833

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [74]:
import numpy as np
n = np.arange(0, 10*np.pi, 0.1)
n1 = 1
x = n1*n*np.cos(n)
y = n1*n*np.sin(n)

n2 = (np.diff(x)**2 + np.diff(y)**2)**.5 
n3 = np.zeros_like(x)
n3[1:] = np.cumsum(n2)                
n3_int = np.linspace(0, n3.max(), 200) 
x_int = np.interp(n3_int, n3, x)       
y_int = np.interp(n3_int, n3, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [75]:
import numpy as np
n1 = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
n2 = np.logical_and.reduce(np.mod(n1, 1) == 0, axis=-1)
n2 &= (n1.sum(axis=-1) == n)
print(n1[n2])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [76]:
import numpy as np
n = np.random.randn(100) # random 1D array
n1 = 1000 # number of bootstrap samples
n2 = np.random.randint(0, n.size, (n1, n.size))
means = n[n2].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.33441976  0.03820451]
